apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-management
spec:
  selector:
    matchLabels:
      app: book-management
  template:
    metadata: 
      labels: 
        app: book-management
    spec: 
      containers:
        - name: book-management-api
        image: book-management-api
        env: 
          - name: ASPNETCORE_ENVIRONMENT
          value: $env_type
        ports: 
          - containerPort: 5000



