
services: 
    books-management-api:
        image: book-management-api
        container_name: book-management-api
        hostname: book-management-api
        build: 
            context: ./src/gestao-livros-api
            dockerfile: BooksManagement.Api/Dockerfile
        environment:
            ASPNETCORE_ENVIRONMENT: $env_type
        ports: 
            - "5000:80"
        networks:
            - default
            - localhost
                
    books-management-app:
        image: book-management-app
        container_name: book-management-app
        hostname: book-management-app
        build: 
            context: ./src/client-app
            args:
                NODE_ENV: $env_type
        ports: 
            - "3000:80"
        networks:
            - default

networks:
    localhost:
        external: true



            