apiVersion: v1
kind: Service
metadata:
  name: book-management-api-service
spec:
  selector:
    app: book-management-api
  ports:
      - port: 5000
        targetPort: 5000
  type: LoadBalancer
      

---
apiVersion: v1
kind: Service
metadata:
  name: book-management-app-service
spec:
  selector:
    app: book-management-app
  ports:
      - port: 3000
        targetPort: 3000
  type: ClusterIP
